export class GlChequesDto{
	   id:number;
       tenantID:number;
       docID:number;
       typeID:string;	
	   entryDate:Date;
	   chequeDate:Date;
	   statusDate:Date;
	   chequeNo:string;
	   chequeAmt:number;
	   chequeStatus:string;
	   partyBank:string;
       chequeRef:string;
	   remarks:string;
	   locationID:number;
	   locDesc:string;
	   accountID:string;
	   accountName:string;
	   partyID:number;
	   partyName:string;
	   bankID:string;
	   bankName:string;
	   chType:number;
	   bankAccountID:string;
	   configID:number;
	   posted:boolean;
	   linkDetID:number;
}